### ISSUE TITLE
iOS sharing apps

### ISSUE THREAD

**Issue by omeriko** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#178]
Hi Eddy, 

You mention in the documentation that in iOS: "you are limited to 'com.apple.social.[facebook | twitter | sinaweibo | tencentweibo]'". 

Does it mean that i can use this plugin on iOS with only the following 4 apps: 
com.apple.social.facebook
com.apple.social.twitter
com.apple.social.sinaweibo
com.apple.social.tencentweibo

What about WhatsApp & Gmail? 

Regards
Omer

**Comment by Seanmclem** [comment]
@EddyVerbruggen Is this still true, now that 6 years has gone by?

**Comment by Seanmclem** [comment]
Based on Stack overflow questions and answers like [this one](https://stackoverflow.com/questions/33106359/socialsharing-phonegap-plugin-cansharevia-check-whether-whatsapp-is-available), it seems like you can definitely use more apps than those 4 using shareVia, as long as you whitelist them. It seems like more share targets are possible since iOS 8 and beyond. I can do more research and maybe make a PR on the README. 

If there is a problem, please reply. I'm not sure why delete the comment.
