### ISSUE TITLE
Is this plugin working with phonegap build 3.6.3 version under wp8?

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#204]
I used this plugin in my app in android, ios and wp8 without problems in phonegap build, but after using the version 3.6.3 of phonegap it stop working in wp8 app, but works well in the other platforms...

Anyone with the same problem?

**Comment by JefferE** [comment]
I can't get the plugin to work in PhoneGap Build 3.6.3 at all (on iOS 8.1.3).

Config.xml has: 

< gap:plugin name="nl.x-services.plugins.socialsharing" version="4.3.8" / > 

index.html has: 

< script type="text/javascript" charset="utf-8" src="cordova.js"></ script > 

JS in deviceready: 

    alert("before plugin-call");
    window.plugins.socialsharing.share('Message test');
    alert("after plugin-call");

Never pops the share window or makes it to the second alert and as far as I can tell its because no part of: window.plugins.socialsharing.share exists except the root window object.

I've got other plugins I'm using the same way and they work.

**Comment by stackdevdev14** [comment]
Hey Jeff, 

I've had a similar issue. Try using <gap:plugin name="nl.x-services.plugins.socialsharing" source="plugins.cordova.io" />

In your config.xml instead. Should hopefully remedy your issue.

Austin

**Comment by JefferE** [comment]
YES!

That fixed it Austin, thanks! Not sure how you ever figured that out.
