### ISSUE TITLE
Confusion on basic plugin calling

### ISSUE THREAD

**Issue by JefferE** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#283]
I'm not sure if this is the proper place for this but can't find a general forum for discussing this plugin.

The docs have this section: http://screencast.com/t/6WCL9MgXRNw

So is the basic method to just call the share function and passing all those possible parameters to it and let the native sharing feature share the pieces that each platform is capable of?

Or is there a way to call it providing the parms each platform can take and the appropriate parms will be used by the platform the user chooses from the sharing feature?

Or do I need to build an interface and have buttons (like your examples) on it that trigger a call to each individual platform with appropriate parms?

The problem I see with the generic first method is that email doesn't support a link parm so if you want a link to be shared you have to put the link in the message. But then that message, with an embedded link, would be used by all the other platforms and I'm not sure they are capable of doing that.

**Comment by EddyVerbruggen** [comment]
The behavior of this plugin matches this description you gave: "So is the basic method to just call the share function and passing all those possible parameters to it and let the native sharing feature share the pieces that each platform is capable of?"

There is no way to intercept which app has been chosen from the standard dialog by the user.

Because of the inflexibility of that approach I have provided additional methods so you can use it in specific ways that seem appropriate for your apps needs.

**Comment by JefferE** [comment]
OK, thanks for the quick reply, just wanted to make sure I wasn't missing something.
