### ISSUE TITLE
Facebook Sharing not working correctly

### ISSUE THREAD

**Issue by splatterb0y** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#297]
``` javascript 
window.plugins.socialsharing.share('Message only')"
```

works on Android 5 but "Message only" is not correctly forwarded to the Facebook Application if I select to share it via Facebook. Facebook App for Android  is the newest version available.

**Comment by mliu95** [comment]
From the readme:

Facebook Android: sharing a message is not possible. You can share either a link or an image (not both), but a description can not be prefilled. See this Facebook issue which they won't solve. As an alternative you can use shareViaFacebookWithPasteMessageHint since plugin version 4.3.4. See below for details. Also note that sharing a URL on a non standard domain (like .fail) may not work on Android. Make sure you test this. You can use a link shortener to workaround this issue.

You can't prefill messages for Facebook on Android sharing

**Comment by splatterb0y** [comment]
Stupid me. Thanks for pointing me to it @mliu95.
