### ISSUE TITLE
Canceling share calls the success callback

### ISSUE THREAD

**Issue by mohamed-karara** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#343]
i am using IOS 7 on iphone 5 to test and when i share using facebook and press cancel button the success callback is called

**Comment by rogercrandall** [comment]
i noticed this as well

**Comment by samuelmeireles** [comment]
+1. Is the a way to detect cancelling?

**Comment by rogercrandall** [comment]
I don't understand. Could you explain?

**Comment by rogercrandall** [comment]
window.plugins.socialsharing.shareViaTwitter(''body of post","image", "url", function() { functionThatWillRunIfPosted() }, function(errormsg){ })

That shows how it works in twitter.. In the Facebook one, if runs the functionThatWillRunIfPosted() even if you hit cancel.

**Comment by EddyVerbruggen** [comment]
Fb recently updated their app and provided their own iOS share widget. Previously they used the built-in share widget.

One of the things they changed was that you're no longer able to prefill the message when sharing to Fb.

Another is a bug: when 'cancel' is pressed, the Fb widget returns 'SLComposeViewControllerResultDone' instead of 'SLComposeViewControllerResultCancelled' which it did previously. You may want to file a bug with Facebook as the plugin is simply calling the callback based on the 'SLComposeViewControllerResult' it receives from the share widget.

In essence, still, as with Android, don't rely on those callbacks.
