### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by kartagis** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#414]
Hi,

I've got the below code

`$("#email").on("click", function() {
    window.plugins.socialsharing.shareViaEmail('http://www.rejicast.com/node/'+nid);
});`

but that gives me `Uncaught TypeError: Cannot read property 'socialsharing' of undefined` but it works beautifully in the console.

**Comment by EddyVerbruggen** [comment]
Hi,

What platform are your running this on (browser perhaps?) and what's the console?

Thx,
Eddy

**Comment by kartagis** [comment]
Hi,

By console I mean chrome://inspect and I'm running on android 4.4.4

**Comment by EddyVerbruggen** [comment]
So in the console your insert that line and the email app opens on your remotely debugged app, is that it?

Can you first check these?
* Do you load cordova.js
* Does `deviceready` fire at all (and before calling a plugin)

**Comment by kartagis** [comment]
Yes I load cordova.js
I didn't know deviceready was needed, let me try that and get back to you.

**Comment by EddyVerbruggen** [comment]
It's not needed perse, but if `deviceready` doesn't fire, plugins are not available. So it's really the first thing to check before pointing the finger at a plugin ;)

If all looks fine on your end please share your project with me.

**Comment by kartagis** [comment]
I really had no idea `deviceready` was needed to load a plugin into the project. When I'm done, if I get permission from the client, I'll share it with you.

Thanks,
Tolga

**Comment by EddyVerbruggen** [comment]
To be clear: `deviceready` isn't required to load a plugin into the project, sorry if that didn't come across correctly.

`deviceready` is fired when `cordova.js` was loaded on a device and Cordova is done prepping the app. Then it fires a JS event to let the webview know it can call into native code again. That's also when plugins will start to work, so basically it's best to not do any plugin calls until `deviceready` fires.

Usually it fires after a sec or so, so binding a handler to a button is mostly safe because the plugin would be available before the user can tap the button anyway. So I'm curious what we'll find out in your case.

**Comment by kartagis** [comment]
Okay, currently I have https://gist.github.com/c39a7172ac3fe757fec0 and I get nothing in console when I click on the device, but Uncaught TypeError: Cannot read property 'socialsharing' of undefined if I fire it manually. If I add the deviceready listener at the beginning of the file, I can't get a list.

**Comment by EddyVerbruggen** [comment]
Please share your entire project with me. Strip out anything not related to this issue and email it at eddyverbruggen at gmail dot com. Thx.
