### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.plugins.socialsharing')

### ISSUE THREAD

**Issue by aralzaim** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#503]
I just found the library you have created, trying to use it for the first time, I have installed the plugin and I am able to see it in my xcode, android studio when I import my project. However, I get the following error whenever I call the function which includes the code below:

window.plugins.socialsharing.share('MyMessage',null,null,'http://www.google.com');

the error I get is:

TypeError: undefined is not an object (evaluating 'window.plugins.socialsharing')

I would really appreciate if you can give any support about this error.

**Comment by EddyVerbruggen** [comment]
Can be many things..
- Have you included a reference to `cordova.js`?
- Are you waiting for `deviceready` to fire?
- Did you install the plugin using `cordova plugin add ..`?

Since this is more a 'how do plugins work' issue (not really specific to this one) I'm closing this. Please follow up on SO if those hints above don't help.

**Comment by kejsiStruga** [comment]
Hi, Any solutions?

**Comment by tpatel27** [comment]
I wanna share the image and followed all the instructions you have put but still showing this
"share_image — Grihasti.html:198TypeError: undefined is not an object (evaluating 'window.plugins.socialsharing')" only you can help as I am following your instructions
thank you
