### ISSUE TITLE
iOS WhatsApp sharing

### ISSUE THREAD

**Issue by Fabioloza** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#572]
So I saw the thread about not being able to use .share() function with WhatsApp on iOS due to their updates - but would be useful if the .share() function had a success/error callback which specified which app was selected by user - in that case we can see if the app selected was whatsapp and we can then invoke the share via whatsapp using the whatsapp://share method.

Just a thought? That way we can still keep one unified share icon for users - because right now the option is to have a "general share" and then a "share with whatsapp" icon, which isn't ideal from a usability standpoint.

**Comment by EddyVerbruggen** [comment]
That's possible but it will break the API a bit since `share` now returns a boolean and I'd need it to return a JSON object. Something like this:

```js
{
   completed: true,
   app: 'net.whatsapp.WhatsApp.ShareExtension'
}
```

I think it's time to take that pain though.

What still bothers me is that WhatsApp will flag the share as completed successfully even if the user cancels sharing. Most iOS apps get this right though.

**Comment by Fabioloza** [comment]
Yeah that does sound frustrating... although if user has managed to share to whatsapp, but cancels themselves - it should return success because the functionality worked, so to say...

Think as long as we could at least invoke the share to whatsapp on fail (as it currently handles) - that would be a huge win. Your JSON structure definitely is the way to go about it!

**Comment by EddyVerbruggen** [comment]
Your usecase will indeed be served by this change, and I'll make it happen.

About the other thing: the problem is that iOS receives a 'completed' flag from the upstream app (mail/whatsapp/whatnot) and it's supposed to ONLY set that to true in case the upstream app actually shared something. But even upon cancel WhatsApp returns true (most others return completed=false in this case). Anyway 🍻

**Comment by Fabioloza** [comment]
Right... got you. I blame Zuckerberg.

**Comment by Fabioloza** [comment]
Heya Eddy - me again! Assuming your update to bug report #571 addresses my issue above as well? (the commit for iOS which includes the new .shareWithOptions method)? Thanks!

**Comment by EddyVerbruggen** [comment]
If you try `shareWithOptions` and get this in the success callback:

```
{
   completed: false,
   app: 'net.whatsapp.WhatsApp.ShareExtension'
}
```

Then you can call direct whatsapp share without showing feedback to the user between those calls.

**Comment by Fabioloza** [comment]
Legend... will implement in due course and feedback! Thanks Eddy.

**Comment by belici** [comment]
Hello Fabioloza, have you tried it already? Does this fallback-approach to share directly via WhatsApp work fluently?

**Comment by Fabioloza** [comment]
Hey @belici sorry no, haven't had a chance yet to check it out - have been prioritising other features in the app build meanwhile. Will holler if and when I do get around to it, if you haven't first :)

**Comment by Fabioloza** [comment]
@EddyVerbruggen finally got round to testing this today - worked like a bomb. Champ! @belici
